<a href="https://colab.research.google.com/github/BigamPachhai/DeepLearning/blob/main/Next_word_pred.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
df=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/qoute_dataset.csv")

In [ ]:
df.head()

                                               quote           Author
0  “The world as we have created it is a process ...  Albert Einstein
1  “It is our choices, Harry, that show what we t...     J.K. Rowling
2  “There are only two ways to live your life. On...  Albert Einstein
3  “The person, be it gentleman or lady, who has ...      Jane Austen
4  “Imperfection is beauty, madness is genius and...   Marilyn Monroe

In [ ]:
df['quote'][0]

'“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”'

In [ ]:
df.shape

(3038, 2)

In [ ]:
quotes=df['quote']
quotes.head()

0    “The world as we have created it is a process ...
1    “It is our choices, Harry, that show what we t...
2    “There are only two ways to live your life. On...
3    “The person, be it gentleman or lady, who has ...
4    “Imperfection is beauty, madness is genius and...
Name: quote, dtype: object

In [ ]:
quotes=quotes.str.lower()

In [ ]:
import string
translator=str.maketrans('', '', string.punctuation)
quotes=quotes.apply(lambda x: x.translate(translator))

In [ ]:
quotes.head()

0    “the world as we have created it is a process ...
1    “it is our choices harry that show what we tru...
2    “there are only two ways to live your life one...
3    “the person be it gentleman or lady who has no...
4    “imperfection is beauty madness is genius and ...
Name: quote, dtype: object

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [ ]:
vocab_size=10000
tokenizer=Tokenizer(num_words=vocab_size)
tokenizer.fit_on_texts(quotes)

In [ ]:
word_index=tokenizer.word_index
print(len(word_index))
list(word_index.items())[:10]

8978

[('the', 1),
 ('you', 2),
 ('to', 3),
 ('and', 4),
 ('a', 5),
 ('i', 6),
 ('is', 7),
 ('of', 8),
 ('that', 9),
 ('it', 10)]

In [ ]:
sequence=tokenizer.texts_to_sequences(quotes)

In [ ]:
for i in range(3):
  print(quotes[i])

“the world as we have created it is a process of our thinking it cannot be changed without changing our thinking”
“it is our choices harry that show what we truly are far more than our abilities”
“there are only two ways to live your life one is as though nothing is a miracle the other is as though everything is a miracle”

In [ ]:
for i in range(3):
  print(sequence[i])

[713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10, 145, 12, 809, 104, 752, 70, 2461]
[947, 7, 70, 871, 373, 9, 433, 21, 19, 465, 14, 294, 52, 54, 70, 3676]
[1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329, 93, 7, 5, 1157, 1, 101, 7, 29, 329, 126, 7, 5, 3677]

In [ ]:
X=[]
y=[]

for seq in sequence:
  for i in range(1, len(seq)):
    X.append(seq[:i])
    y.append(seq[i])

In [ ]:
len(X)

85271

In [ ]:
len(y)

85271

In [ ]:
max_len=max(len(x) for x in X)
print(max_len)

745

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
X_padded=pad_sequences(X,maxlen=max_len)

In [ ]:
X_padded

array([[   0,    0,    0, ...,    0,    0,  713],
       [   0,    0,    0, ...,    0,  713,   62],
       [   0,    0,    0, ...,  713,   62,   29],
       ...,
       [   0,    0,    0, ...,    9,   19, 1125],
       [   0,    0,    0, ...,   19, 1125,    3],
       [   0,    0,    0, ..., 1125,    3,  169]], dtype=int32)

In [ ]:
y=np.array(y)

In [ ]:
X_padded.shape

(85271, 745)

In [ ]:
from tensorflow.keras.utils import to_categorical
y_one_hot = to_categorical(y, num_classes=vocab_size)

In [ ]:
y.shape

(85271,)

In [ ]:
y_one_hot.shape

(85271, 10000)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,SimpleRNN, LSTM, Dense

In [ ]:
embedding_dim=50
rnn_units=128

In [ ]:
rnn_model=Sequential()
rnn_model.add(Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_len))

rnn_model.add(SimpleRNN(units=rnn_units))
rnn_model.add(Dense(units=vocab_size, activation='softmax'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [ ]:
rnn_model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [ ]:
rnn_model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
lstm_model = Sequential()
lstm_model.add(
    Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_len)
)
lstm_model.add(LSTM(units=rnn_units))
lstm_model.add(Dense(units=vocab_size, activation='softmax'))

In [ ]:
lstm_model.compile(
    optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy']
)

In [ ]:
lstm_model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
epochs=10
batch_size=128

In [ ]:
history_rnn=rnn_model.fit(X_padded, y_one_hot, epochs=epochs, batch_size=batch_size,validation_split=0.1)

Epoch 1/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 50s 74ms/step - accuracy: 0.0460 - loss: 6.7358 - val_accuracy: 0.0201 - val_loss: 10.7530
Epoch 2/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 40s 67ms/step - accuracy: 0.0696 - loss: 6.2747 - val_accuracy: 0.0816 - val_loss: 6.4563
Epoch 3/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 40s 67ms/step - accuracy: 0.0936 - loss: 5.9481 - val_accuracy: 0.0950 - val_loss: 6.3460
Epoch 4/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 40s 67ms/step - accuracy: 0.1067 - loss: 5.7062 - val_accuracy: 0.1004 - val_loss: 6.3654
Epoch 5/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 40s 67ms/step - accuracy: 0.1178 - loss: 5.5130 - val_accuracy: 0.1041 - val_loss: 6.3377
Epoch 6/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 40s 67ms/step - accuracy: 0.1293 - loss: 5.3315 - val_accuracy: 0.1065 - val_loss: 6.3352
Epoch 7/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 40s 67ms/step - accuracy: 0.1381 - loss: 5.1392 - val_accuracy: 0.1080 - val_loss: 6.3900
Epoch 8/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 42s 71ms/step - accuracy: 0.1486 - loss: 4.9616 - val_accuracy: 0.1073 - val_loss: 6.4285
Epoch 9/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 40s 67ms/step - accuracy: 0.1595 - loss: 4.7880 - val_accuracy: 0.1082 - val_loss: 6.4595
Epoch 10/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 40s 67ms/step - accuracy: 0.1717 - loss: 4.6139 - val_accuracy: 0.1092 - val_loss: 6.5198

In [ ]:
epochs=100
batch_size=128
history_lstm=lstm_model.fit(X_padded, y_one_hot, epochs=epochs, batch_size=batch_size,validation_split=0.1)

Epoch 1/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 40s 56ms/step - accuracy: 0.0390 - loss: 6.7576 - val_accuracy: 0.0469 - val_loss: 6.6880
Epoch 2/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.0587 - loss: 6.3275 - val_accuracy: 0.0655 - val_loss: 6.5520
Epoch 3/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.0819 - loss: 6.0474 - val_accuracy: 0.0829 - val_loss: 6.4648
Epoch 4/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.0989 - loss: 5.8250 - val_accuracy: 0.0946 - val_loss: 6.4318
Epoch 5/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.1108 - loss: 5.6349 - val_accuracy: 0.1001 - val_loss: 6.4113
Epoch 6/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.1214 - loss: 5.4583 - val_accuracy: 0.1061 - val_loss: 6.4151
Epoch 7/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.1296 - loss: 5.3006 - val_accuracy: 0.1074 - val_loss: 6.4447
Epoch 8/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.1380 - loss: 5.1551 - val_accuracy: 0.1079 - val_loss: 6.4788
Epoch 9/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.1441 - loss: 5.0179 - val_accuracy: 0.1119 - val_loss: 6.5348
Epoch 10/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.1516 - loss: 4.8875 - val_accuracy: 0.1095 - val_loss: 6.5700
Epoch 11/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.1575 - loss: 4.7587 - val_accuracy: 0.1113 - val_loss: 6.6283
Epoch 12/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.1653 - loss: 4.6340 - val_accuracy: 0.1121 - val_loss: 6.6654
Epoch 13/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.1730 - loss: 4.5121 - val_accuracy: 0.1123 - val_loss: 6.7297
Epoch 14/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.1818 - loss: 4.3886 - val_accuracy: 0.1120 - val_loss: 6.7965
Epoch 15/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.1942 - loss: 4.2672 - val_accuracy: 0.1144 - val_loss: 6.8703
Epoch 16/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.2073 - loss: 4.1506 - val_accuracy: 0.1129 - val_loss: 6.9426
Epoch 17/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.2208 - loss: 4.0397 - val_accuracy: 0.1112 - val_loss: 7.0263
Epoch 18/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 54ms/step - accuracy: 0.2360 - loss: 3.9308 - val_accuracy: 0.1117 - val_loss: 7.0992
Epoch 19/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.2505 - loss: 3.8299 - val_accuracy: 0.1121 - val_loss: 7.1820
Epoch 20/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.2650 - loss: 3.7347 - val_accuracy: 0.1094 - val_loss: 7.2509
Epoch 21/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 42s 56ms/step - accuracy: 0.2793 - loss: 3.6450 - val_accuracy: 0.1107 - val_loss: 7.3274
Epoch 22/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.2919 - loss: 3.5605 - val_accuracy: 0.1093 - val_loss: 7.4138
Epoch 23/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.3040 - loss: 3.4824 - val_accuracy: 0.1108 - val_loss: 7.4919
Epoch 24/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.3172 - loss: 3.4066 - val_accuracy: 0.1085 - val_loss: 7.5610
Epoch 25/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.3279 - loss: 3.3362 - val_accuracy: 0.1062 - val_loss: 7.6392
Epoch 26/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.3388 - loss: 3.2705 - val_accuracy: 0.1072 - val_loss: 7.7144
Epoch 27/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.3492 - loss: 3.2068 - val_accuracy: 0.1082 - val_loss: 7.7889
Epoch 28/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.3575 - loss: 3.1458 - val_accuracy: 0.1039 - val_loss: 7.8550
Epoch 29/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.3688 - loss: 3.0857 - val_accuracy: 0.1038 - val_loss: 7.9304
Epoch 30/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.3781 - loss: 3.0295 - val_accuracy: 0.1028 - val_loss: 7.9913
Epoch 31/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.3866 - loss: 2.9746 - val_accuracy: 0.1041 - val_loss: 8.0585
Epoch 32/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.3954 - loss: 2.9215 - val_accuracy: 0.1042 - val_loss: 8.1312
Epoch 33/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.4048 - loss: 2.8698 - val_accuracy: 0.1037 - val_loss: 8.1890
Epoch 34/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.4124 - loss: 2.8212 - val_accuracy: 0.1040 - val_loss: 8.2487
Epoch 35/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.4205 - loss: 2.7721 - val_accuracy: 0.1026 - val_loss: 8.3241
Epoch 36/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.4290 - loss: 2.7266 - val_accuracy: 0.1007 - val_loss: 8.3940
Epoch 37/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4363 - loss: 2.6820 - val_accuracy: 0.1019 - val_loss: 8.4351
Epoch 38/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4445 - loss: 2.6361 - val_accuracy: 0.1011 - val_loss: 8.4846
Epoch 39/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.4519 - loss: 2.5925 - val_accuracy: 0.1000 - val_loss: 8.5690
Epoch 40/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.4596 - loss: 2.5520 - val_accuracy: 0.0980 - val_loss: 8.6243
Epoch 41/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4669 - loss: 2.5105 - val_accuracy: 0.0996 - val_loss: 8.6740
Epoch 42/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.4741 - loss: 2.4715 - val_accuracy: 0.0966 - val_loss: 8.7460
Epoch 43/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.4819 - loss: 2.4332 - val_accuracy: 0.0974 - val_loss: 8.8023
Epoch 44/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4889 - loss: 2.3955 - val_accuracy: 0.0962 - val_loss: 8.8574
Epoch 45/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.4946 - loss: 2.3578 - val_accuracy: 0.0987 - val_loss: 8.9247
Epoch 46/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 42s 56ms/step - accuracy: 0.5021 - loss: 2.3234 - val_accuracy: 0.0955 - val_loss: 8.9646
Epoch 47/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5091 - loss: 2.2867 - val_accuracy: 0.0972 - val_loss: 9.0310
Epoch 48/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5154 - loss: 2.2530 - val_accuracy: 0.0953 - val_loss: 9.0875
Epoch 49/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5224 - loss: 2.2198 - val_accuracy: 0.0946 - val_loss: 9.1391
Epoch 50/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.5285 - loss: 2.1871 - val_accuracy: 0.0943 - val_loss: 9.2035
Epoch 51/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5362 - loss: 2.1551 - val_accuracy: 0.0912 - val_loss: 9.2592
Epoch 52/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5408 - loss: 2.1253 - val_accuracy: 0.0932 - val_loss: 9.3307
Epoch 53/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5471 - loss: 2.0944 - val_accuracy: 0.0943 - val_loss: 9.3649
Epoch 54/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5530 - loss: 2.0644 - val_accuracy: 0.0915 - val_loss: 9.4253
Epoch 55/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5595 - loss: 2.0347 - val_accuracy: 0.0912 - val_loss: 9.4645
Epoch 56/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5646 - loss: 2.0075 - val_accuracy: 0.0923 - val_loss: 9.5424
Epoch 57/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.5696 - loss: 1.9792 - val_accuracy: 0.0916 - val_loss: 9.6018
Epoch 58/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5756 - loss: 1.9537 - val_accuracy: 0.0906 - val_loss: 9.6333
Epoch 59/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 54ms/step - accuracy: 0.5813 - loss: 1.9262 - val_accuracy: 0.0890 - val_loss: 9.6973
Epoch 60/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.5860 - loss: 1.9001 - val_accuracy: 0.0894 - val_loss: 9.7453
Epoch 61/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.5915 - loss: 1.8751 - val_accuracy: 0.0903 - val_loss: 9.8152
Epoch 62/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5955 - loss: 1.8506 - val_accuracy: 0.0864 - val_loss: 9.8579
Epoch 63/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6014 - loss: 1.8259 - val_accuracy: 0.0858 - val_loss: 9.9055
Epoch 64/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.6060 - loss: 1.8025 - val_accuracy: 0.0860 - val_loss: 9.9615
Epoch 65/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.6104 - loss: 1.7798 - val_accuracy: 0.0876 - val_loss: 10.0251
Epoch 66/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6161 - loss: 1.7572 - val_accuracy: 0.0874 - val_loss: 10.0583
Epoch 67/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6207 - loss: 1.7348 - val_accuracy: 0.0838 - val_loss: 10.1074
Epoch 68/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6240 - loss: 1.7127 - val_accuracy: 0.0868 - val_loss: 10.1510
Epoch 69/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.6281 - loss: 1.6916 - val_accuracy: 0.0843 - val_loss: 10.2202
Epoch 70/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6336 - loss: 1.6690 - val_accuracy: 0.0881 - val_loss: 10.2793
Epoch 71/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.6367 - loss: 1.6490 - val_accuracy: 0.0850 - val_loss: 10.3350
Epoch 72/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6419 - loss: 1.6288 - val_accuracy: 0.0861 - val_loss: 10.3760
Epoch 73/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6461 - loss: 1.6094 - val_accuracy: 0.0845 - val_loss: 10.4254
Epoch 74/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 54ms/step - accuracy: 0.6496 - loss: 1.5919 - val_accuracy: 0.0836 - val_loss: 10.4951
Epoch 75/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6541 - loss: 1.5718 - val_accuracy: 0.0804 - val_loss: 10.5233
Epoch 76/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6579 - loss: 1.5536 - val_accuracy: 0.0824 - val_loss: 10.5650
Epoch 77/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6615 - loss: 1.5351 - val_accuracy: 0.0824 - val_loss: 10.6186
Epoch 78/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.6661 - loss: 1.5167 - val_accuracy: 0.0841 - val_loss: 10.6788
Epoch 79/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6706 - loss: 1.4989 - val_accuracy: 0.0831 - val_loss: 10.7162
Epoch 80/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6741 - loss: 1.4802 - val_accuracy: 0.0815 - val_loss: 10.7719
Epoch 81/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 54ms/step - accuracy: 0.6783 - loss: 1.4645 - val_accuracy: 0.0833 - val_loss: 10.8169
Epoch 82/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6805 - loss: 1.4492 - val_accuracy: 0.0826 - val_loss: 10.8613
Epoch 83/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6855 - loss: 1.4325 - val_accuracy: 0.0804 - val_loss: 10.9336
Epoch 84/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6875 - loss: 1.4161 - val_accuracy: 0.0828 - val_loss: 10.9646
Epoch 85/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6910 - loss: 1.4006 - val_accuracy: 0.0794 - val_loss: 11.0224
Epoch 86/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6934 - loss: 1.3862 - val_accuracy: 0.0804 - val_loss: 11.0669
Epoch 87/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6982 - loss: 1.3688 - val_accuracy: 0.0777 - val_loss: 11.1196
Epoch 88/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.7000 - loss: 1.3578 - val_accuracy: 0.0779 - val_loss: 11.1555
Epoch 89/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.7041 - loss: 1.3423 - val_accuracy: 0.0784 - val_loss: 11.2085
Epoch 90/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.7071 - loss: 1.3272 - val_accuracy: 0.0800 - val_loss: 11.2543
Epoch 91/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.7110 - loss: 1.3127 - val_accuracy: 0.0782 - val_loss: 11.3065
Epoch 92/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.7135 - loss: 1.2985 - val_accuracy: 0.0793 - val_loss: 11.3569
Epoch 93/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 55ms/step - accuracy: 0.7155 - loss: 1.2853 - val_accuracy: 0.0784 - val_loss: 11.3977
Epoch 94/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 55ms/step - accuracy: 0.7187 - loss: 1.2703 - val_accuracy: 0.0787 - val_loss: 11.4486
Epoch 95/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 55ms/step - accuracy: 0.7213 - loss: 1.2601 - val_accuracy: 0.0762 - val_loss: 11.4871
Epoch 96/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.7253 - loss: 1.2458 - val_accuracy: 0.0768 - val_loss: 11.5409
Epoch 97/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.7275 - loss: 1.2338 - val_accuracy: 0.0796 - val_loss: 11.6116
Epoch 98/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.7313 - loss: 1.2206 - val_accuracy: 0.0784 - val_loss: 11.6129
Epoch 99/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.7328 - loss: 1.2093 - val_accuracy: 0.0783 - val_loss: 11.6702
Epoch 100/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.7347 - loss: 1.1990 - val_accuracy: 0.0758 - val_loss: 11.7231

In [ ]:
lstm_model.save('lstm_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [ ]:
index_to_word={}
for word,index in word_index.items():
  index_to_word[index]=word

In [ ]:

from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
def predictor(model,tokenizer,text,max_len):
  text = text.lower()

  seq = tokenizer.texts_to_sequences([text])[0]
  seq = pad_sequences([seq], maxlen=max_len, padding='pre')

  pred = model.predict(seq,verbose = 0)
  pred_index = np.argmax(pred)
  return index_to_word[pred_index]

In [ ]:
seed_text = "what are "
next_word = predictor(lstm_model,tokenizer,seed_text,max_len)
print(next_word)

the

In [ ]:
def generate_text(model,tokenizer,seed_text,max_len,n_words):
  for _ in range(n_words):
    next_word = predictor(model,tokenizer,seed_text,max_len)
    if next_word == "":
      break
    seed_text += " " + next_word
  return seed_text

In [ ]:
seed = "Meaning of life"
generated_output = generate_text(lstm_model,tokenizer,seed,max_len,10)
print(generated_output)

Meaning of life is the only options left and laughing feels better to

In [ ]:
import pickle
with open("tokenizer.pkl", "wb") as f:
    pickle.dump(tokenizer, f)

In [ ]:
with open("max_len.pkl", "wb") as f:
    pickle.dump(max_len, f)